### ISSUE TITLE
hello, wonder that what case suit for generate code?

### ISSUE THREAD

**Issue by RichardLiee** [yuchdev/code_generator#5]

**Comment by yuchdev** [comment]
Could you elaborate, please? What's the exact problem

**Comment by masagrator** [comment]
I don't think they have a problem.
They ask about practical use of this library.

I prefer to use Python to work on json, but for example I would need to implement data stored inside it to C++ because reasons, and found this library. Didn't test yet if it's possible to parse those data to header with static std::vector, but looking at code I think it's possible.

**Comment by antonysigma** [comment]
One niche application is to accelerate a data heavy processing pipeline with `pycuda`. Most of the time, the only way to emit CUDA/C++ code from Python just-in-time is to rely on `str.format()` API to format the C++ code as strings. Here is one example:

https://github.com/comp-imaging/ProxImaL/blob/master/proximal/lin_ops/conv_nofft.py#L97-L135

**Comment by yuchdev** [comment]
Ah, about this. Real practical cases are: create compile-time datasets from external sources, generate unit-tests.
In theory, could be useful for "translation" from one language to another.
